-- Test and Analytical Queries for Gym Management System

-- 1. List members with their gym and plan
SELECT 
    M.First_name || ' ' || M.Last_name AS Member_Name,
    G.Gym_name,
    P.Plan_name
FROM Member M
JOIN Gym G ON M.Gym_id = G.Gym_id
JOIN Plan P ON M.Plan_id = P.Plan_id;

-- 2. Total revenue generated by each gym
SELECT 
    G.Gym_name,
    SUM(P.Amount_paid) AS Total_Revenue
FROM Payment P
JOIN Member M ON P.M_id = M.M_id
JOIN Gym G ON M.Gym_id = G.Gym_id
GROUP BY G.Gym_name;

-- 3. Facilities included in each plan
SELECT 
    P.Plan_name,
    F.Facility_name
FROM PlanFacility PF
JOIN Plan P ON PF.Plan_id = P.Plan_id
JOIN Facility_ F ON PF.F_id = F.F_id
ORDER BY P.Plan_name;

-- 4. Members who joined after 1st September 2025
SELECT 
    First_name,
    Last_name,
    Join_date
FROM Member
WHERE Join_date > DATE '2025-09-01';

-- 5. Member payment details
SELECT 
    M.M_id,
    M.First_name,
    M.Last_name,
    M.Phone,
    M.Address,
    P.Amount_paid,
    P.Payment_date,
    P.Payment_mode
FROM Member M
JOIN Payment P ON M.M_id = P.M_id;

-- 6. Remaining membership days for members
SELECT 
    M.First_name,
    M.Last_name,
    M.Join_date,
    (P.Duration_days - (SYSDATE - M.Join_date)) AS Remaining_Days
FROM Member M
JOIN Plan P ON M.Plan_id = P.Plan_id;

