-- Gym Management System Database Schema
-- Author: Krishna Tyagi
-- Tool: Oracle SQL / Oracle APEX

-- Drop old tables if re-running
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE Member CASCADE CONSTRAINTS';
  EXECUTE IMMEDIATE 'DROP TABLE Payment CASCADE CONSTRAINTS';
  EXECUTE IMMEDIATE 'DROP TABLE Gym CASCADE CONSTRAINTS';
  EXECUTE IMMEDIATE 'DROP TABLE User_ CASCADE CONSTRAINTS';
  EXECUTE IMMEDIATE 'DROP TABLE PlanFacility CASCADE CONSTRAINTS';
  EXECUTE IMMEDIATE 'DROP TABLE Plan CASCADE CONSTRAINTS';
  EXECUTE IMMEDIATE 'DROP TABLE Facility_ CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

-- =========================
-- Table: Plan
-- =========================
CREATE TABLE Plan (
  Plan_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  Plan_name VARCHAR2(50) NOT NULL,
  Duration_days NUMBER,
  Cost NUMBER
);

-- =========================
-- Table: Facility
-- =========================
CREATE TABLE Facility_ (
  F_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  Facility_name VARCHAR2(50) NOT NULL
);

-- =========================
-- Table: PlanFacility (Bridge Table)
-- =========================
CREATE TABLE PlanFacility (
  Plan_id NUMBER NOT NULL,
  F_id NUMBER NOT NULL,
  PRIMARY KEY (Plan_id, F_id),
  FOREIGN KEY (Plan_id) REFERENCES Plan(Plan_id),
  FOREIGN KEY (F_id) REFERENCES Facility_(F_id)
);

-- =========================
-- Table: User
-- =========================
CREATE TABLE User_ (
  U_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username VARCHAR2(50) UNIQUE NOT NULL,
  role VARCHAR2(30),
  password VARCHAR2(50),
  Gym_id NUMBER
);

-- =========================
-- Table: Gym
-- =========================
CREATE TABLE Gym (
  Gym_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  Gym_name VARCHAR2(50) NOT NULL,
  Address VARCHAR2(100),
  Phone VARCHAR2(15),
  Email VARCHAR2(100),
  Plan_id NUMBER,
  U_id NUMBER,
  FOREIGN KEY (Plan_id) REFERENCES Plan(Plan_id),
  FOREIGN KEY (U_id) REFERENCES User_(U_id)
);

-- =========================
-- Table: Member
-- =========================
CREATE TABLE Member (
  M_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  First_name VARCHAR2(30),
  Middle_name VARCHAR2(30),
  Last_name VARCHAR2(30),
  Phone VARCHAR2(15),
  Status VARCHAR2(15),
  Address VARCHAR2(100),
  Join_date DATE,
  Plan_id NUMBER,
  Gym_id NUMBER,
  FOREIGN KEY (Plan_id) REFERENCES Plan(Plan_id),
  FOREIGN KEY (Gym_id) REFERENCES Gym(Gym_id)
);

-- =========================
-- Table: Payment
-- =========================
CREATE TABLE Payment (
  P_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  M_id NUMBER,
  Amount_paid NUMBER,
  Payment_date DATE,
  Payment_mode VARCHAR2(30),
  FOREIGN KEY (M_id) REFERENCES Member(M_id)
);

